# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Advanced Micro Devices, Inc. All rights reserved.

name: Lint & Auto-Fix

run-name: Linting, formatting, fixing by ${{ github.actor }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    ROCM_VERSION: 7.1.1
    AMDGPU_INSTALLER_VERSION: 7.1.1.70101-1

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install ROCm Dev
        run: |
          wget https://repo.radeon.com/amdgpu-install/${{ env.ROCM_VERSION }}/ubuntu/noble/amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb
          apt-get -y install ./amdgpu-install_${{ env.AMDGPU_INSTALLER_VERSION }}_all.deb &&
          apt-get update -qq &&
          apt-get -y install rocm-dev rocm-llvm-dev
          echo "/opt/rocm/bin" >> $GITHUB_PATH
          echo "ROCM_PATH=/opt/rocm" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/opt/rocm/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
          apt-get autoclean

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 'latest'

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run ruff check
        run: ruff check --fix

      - name: Run ruff format
        run: ruff format

      - name: Fail if formatting changes are needed
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Formatting or linting changes are needed. Please run 'ruff check --fix' and 'ruff format' and commit the changes."
            exit 1
          fi
